export const INGREDIENT_LIST_REQUEST = "INGREDIENT_LIST_REQUEST";
export const INGREDIENT_LIST_SUCCESS = "INGREDIENT_LIST_SUCCESS";
export const INGREDIENT_LIST_FAIL = "INGREDIENT_LIST_FAIL";
export const INGREDIENT_LIST_RESET = "INGREDIENT_LIST_RESET";

export const INGREDIENT_CREATE_REQUEST = "INGREDIENT_CREATE_REQUEST";
export const INGREDIENT_CREATE_SUCCESS = "INGREDIENT_CREATE_SUCCESS";
export const INGREDIENT_CREATE_FAIL = "INGREDIENT_CREATE_FAIL";

export const INGREDIENT_DETAILS_REQUEST = "INGREDIENT_DETAILS_REQUEST";
export const INGREDIENT_DETAILS_SUCCESS = "INGREDIENT_DETAILS_SUCCESS";
export const INGREDIENT_DETAILS_FAIL = "INGREDIENT_DETAILS_FAIL";
export const INGREDIENT_DETAILS_RESET = "INGREDIENT_DETAILS_RESET";

export const INGREDIENT_UPDATE_REQUEST = "INGREDIENT_UPDATE_REQUEST";
export const INGREDIENT_UPDATE_SUCCESS = "INGREDIENT_UPDATE_SUCCESS";
export const INGREDIENT_UPDATE_FAIL = "INGREDIENT_UPDATE_FAIL";
export const INGREDIENT_UPDATE_RESET = "INGREDIENT_UPDATE_RESET";

export const INGREDIENT_DELETE_REQUEST = "INGREDIENT_DELETE_REQUEST";
export const INGREDIENT_DELETE_SUCCESS = "INGREDIENT_DELETE_SUCCESS";
export const INGREDIENT_DELETE_FAIL = "INGREDIENT_DELETE_FAIL";
export const INGREDIENT_DELETE_RESET = "INGREDIENT_DELETE_RESET";
